title: 'coderhh.github.io'
description: 'A jekyll theme inspired by linux consoles for hackers, developers and script kiddies.'
baseurl: ''
url: 'https://coderhh.github.io'

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

plugins:
  - jekyll-remote-theme

style: hacker

footer: 'follow me on <a href="https://twitter.com/YehangH">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
#theme: jekyll-theme-console
